### ISSUE TITLE
Newsletters load in batches and appear in random intervals

### ISSUE THREAD

**Issue by jurajpal** [nicholaschiang/newsletter#12]
https://www.loom.com/share/f29fda7636534776ba4965f4af9066b1

**Comment by nicholaschiang** [comment]
@jurajpal Next time, if you can, just embed the video straight into the GitHub issue (there's a lot of benefits to that e.g. GitHub CLI can make viewing all issues at the same time a lot easier).

Yeah, I can update this. It'll feel slower for the initial load though. Essentially, what it's doing now is just loading the newsletters in batches of 50 emails:
1. Show fallback loading state.
2. Fetch the first 50 emails from Gmail's API and filter out any newsletters in those emails' senders.
3. Show those newsletters in the list and hide the fallback state.
4. Keep loading in batches of 50 emails (a total of ~5000 emails I think).

Instead, I could just fetch all ~1000 emails (from which I filter newsletters) first and then hide the fallback state. This would make it take a lot slower (~5-10 seconds) and thus that's why I recommended we show a funny GIF while we're loading. It's all about striking a balance between speed (how long it takes for the first results to load) and confusion (e.g. the loading in batches that appears random and seems like a bug).

**Comment by martinsrna** [comment]
Makes sense! We will share a GIF/Image for this, can be very simple.

**Comment by jurajpal** [comment]
@nicholaschiang here's a gif we could use + I'd also include it with a message above it: 'Getting your newsletters'
https://media.giphy.com/media/3o7WIIC8bMnvkFO30Q/giphy.gif

**Comment by nicholaschiang** [comment]
@jurajpal Just to be sure: that's a SpaceX rocket landing, right? This is intentional haha?

**Comment by martinsrna** [comment]
@nicholaschiang Yeah, it might seem a bit off-topic, but looking at Falcon(s) landing never hurts.
